USE db_libmgmtsys1;

	GO
	CREATE PROCEDURE ProgrammedLibQueries
	AS

	SELECT BOOK_COPIES.No_Of_Copies, BOOK.Title, LIBRARY_BRANCH.BranchName FROM BOOK_COPIES 
	FULL OUTER JOIN BOOK on BOOK_COPIES.BookId = BOOK.BookId
	FULL OUTER JOIN LIBRARY_BRANCH on BOOK_COPIES.Branch_id = LIBRARY_BRANCH.BranchId
	WHERE BOOK.BookId = 1 AND Branch_id = 10005;

	SELECT BOOK_COPIES.No_Of_Copies, BOOK.Title, LIBRARY_BRANCH.BranchName FROM BOOK_COPIES 
	FULL OUTER JOIN BOOK on BOOK_COPIES.BookId = BOOK.BookId
	FULL OUTER JOIN LIBRARY_BRANCH on BOOK_COPIES.Branch_id = LIBRARY_BRANCH.BranchId
	WHERE BOOK.BookId = 1;


	SELECT BOOK_LOANS.CardNo, BORROWER.Name FROM BOOK_LOANS 
	FULL OUTER JOIN BORROWER on BOOK_LOANS.CardNo = BORROWER.Cardno
	WHERE BOOK_LOANS.CardNo IS NULL;

	SELECT BOOK.Title, BORROWER.Name, BORROWER.StreetAddress FROM BOOK_LOANS
	FULL OUTER JOIN LIBRARY_BRANCH on BOOK_LOANS.BranchId = LIBRARY_BRANCH.BranchId
	FULL OUTER JOIN BOOK on BOOK_LOANS.BookId = BOOK.BookId
	FULL OUTER JOIN BORROWER on BOOK_LOANS.CardNo = BORROWER.CardNo
	WHERE LIBRARY_BRANCH.BranchName = 'Sharpstown' AND BOOK_LOANS.DueDate = '04-30-2018';

	SELECT LIBRARY_BRANCH.BranchName, COUNT(BOOK_LOANS.BookId) AS '# of Copies' FROM BOOK_LOANS
	FULL OUTER JOIN LIBRARY_BRANCH on BOOK_LOANS.BranchId = LIBRARY_BRANCH.BranchId
	GROUP BY LIBRARY_BRANCH.BranchName;

	SELECT BORROWER.Name, BORROWER.StreetAddress, COUNT(BOOK_LOANS.BookId) AS '# of Books Checked Out' FROM BOOK_LOANS
	FULL OUTER JOIN BORROWER on BOOK_LOANS.CardNo = BORROWER.CardNo
	GROUP BY BORROWER.Name, BORROWER.StreetAddress
	HAVING COUNT(BOOK_LOANS.BookId) > 5;

	SELECT BOOK.Title, BOOK_COPIES.No_Of_Copies FROM LIBRARY_BRANCH
	FULL OUTER JOIN BOOK_COPIES on BOOK_COPIES.Branch_id = LIBRARY_BRANCH.BranchId
	FULL OUTER JOIN BOOK_AUTHORS on BOOK_AUTHORS.BookId = BOOK_COPIES.BookId
	FULL OUTER JOIN BOOK on Book.BookId = BOOK_COPIES.BookId
	WHERE BOOK_AUTHORS.AuthorName = 'Stephen King' AND BranchName = 'Central';